# Numpy 

# numpy array yapısı

In [1]:
data_list = [1,2,3,4]
data_list

[1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
arr = np.array(data_list)
arr

array([1, 2, 3, 4])

In [6]:
data_list2 = [[1,2,3],[10,20,30],[100,200,300]]
arr2 = np.array(data_list2)
arr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [7]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

In [8]:
arr3[0]

1

In [9]:
arr3[-1]

5

In [10]:
arr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [11]:
arr2[2,2]

300

In [13]:
arr2[0,2]

3

# numpy üzerinde metotlar 

# .arange()

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

# .zeros()

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# .ones()

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# .linespace()

In [21]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

# .eye()

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# .random.randint()

In [25]:
np.random.randint(0,10)

8

In [30]:
np.random.randint(0,10)

0

In [31]:
np.random.randint(1,100,10)

array([22, 23,  3, 26, 37, 56, 46, 21, 31, 51])

# .random.rand()

In [33]:
np.random.rand(5)

array([0.87316712, 0.02936576, 0.33672162, 0.24450312, 0.55712313])

# .random.randn()

In [34]:
np.random.randn(10)

array([-0.99278513,  0.2785292 , -0.88476062,  0.66441949,  0.41469388,
        0.60270863, -0.37854975, -1.18515362, -0.87346292, -0.88449357])

In [35]:
np.random.randn(4)

array([-0.27696212, -1.16109996, -1.04243339, -0.29101996])

# .arange()

arange ile oluşturulan bir diziden matris oluşturmak için reshape metodu kullanılır. Fakat dizinin elemanları ile matrisin boyutu uyumlu olmalıdır. 

In [36]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# .reshape()

# arr.reshape(5,5)

In [38]:
newArray = np.random.randint(1,100,10)

In [39]:
newArray

array([32, 46, 40, 75, 29, 22, 61, 13, 82, 48])

# .min() ve .max()

rastgele oluşturulan bu dizinin en büyük elemanını bulmak için max metodu kullanılır. Bunun aksine ne küçük elemanı bulmak içinde min metodu kullanılır. 

In [40]:
newArray.max()

82

In [41]:
newArray.min()

13

# .sum()

sum methodu ile de array' deki elemanların toplamı alınabilir. mean(metodu ile de array' deki elemanların ortalaması alınır: elemanlar toplamı / eleman sayısı

In [42]:
newArray.sum()

448

# .mean()

In [43]:
newArray.mean()

44.8

# .argmax() ve .argmin()

arraydeki, maximum ve minimum elemanların indis numaraları argmax( ve argmin( metodu ile sorgulanabilir. ))

In [44]:
newArray.argmax()

8

In [45]:
newArray.argmin()

7

# .ndim()

In [4]:
array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [0, 4, 16, 9]])
array3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 0,  4, 16,  9]])

In [5]:
print("boyut (dimension): ", array3.ndim) # boyutunu verir

boyut (dimension):  2


In [6]:
array4 = np.array([i for i in range(1,16)])
array4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
print(array4.shape)

(15,)


In [9]:
a = array4.reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
print("shape of my heart: ", a.shape)
print("boyut (dimension): ", a.ndim) # boyutunu verir
print("data type: ", a.dtype.name) # data type (dtype) verir
print("size: ", a.size) # reshape yapmadan önceki boyutunu verir
print("type: ", type(a))

shape of my heart:  (3, 5)
boyut (dimension):  2
data type:  int32
size:  15
type:  <class 'numpy.ndarray'>


In [12]:
from numpy import linalg

In [14]:
np.linalg.eigvals(array3) # Niçin boyutu 2 çıkıyorun cevabı, vektör uzayında 2 özdeğer dolayısıyla da 2 özvektörü var.

array([ 3.02065429e+01+0.j        , -1.60327143e+00+2.87890523j,
       -1.60327143e+00-2.87890523j,  6.10224687e-16+0.j        ])

# .empty()

In [15]:
empty = np.empty((3,3))
empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.39122206e-321],
       [1.86989318e-306, 2.13451446e-287, 8.18503576e-201]])

# Temel Lineer cebir işlemleri

matrisin determinantı 

In [28]:
arrx = np.random.randint(1,100,25)
arrx

array([26, 97, 77, 62, 50, 90, 59,  7, 89, 95, 59, 91,  4, 41, 32, 86, 88,
       73, 72, 26,  3, 26, 64, 38, 47])

In [29]:
arrx = arrx.reshape(5,5)
arrx

array([[26, 97, 77, 62, 50],
       [90, 59,  7, 89, 95],
       [59, 91,  4, 41, 32],
       [86, 88, 73, 72, 26],
       [ 3, 26, 64, 38, 47]])

In [21]:
np.linalg.det(arrx)

120437700.00000025

In [22]:
arr2 = np.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [23]:
np.linalg.det(arr2)

-2.0000000000000004

In [24]:
round(np.linalg.det(arr2))

-2

In [25]:
round(np.linalg.det(arr2))

-2

In [26]:
arr2

array([[1, 2],
       [3, 4]])

In [27]:
arr2.T

array([[1, 3],
       [2, 4]])

# array' lerin indekslenmesi ve parçalanması 

# numpy slicing and indexing

In [31]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[2]

2

In [33]:
arr[1:5]

array([1, 2, 3, 4])

In [34]:
arr[:4]

array([0, 1, 2, 3])

In [35]:
arr[::2]

array([0, 2, 4, 6, 8])

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[:3] = 100
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [38]:
reverse_array = arr[::-1]
reverse_array

array([  9,   8,   7,   6,   5,   4,   3, 100, 100, 100])

In [39]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr2[:3] = 1000
arr2

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9])

In [42]:
arr

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9])

arr2' de yapılan değişiklik arr' yi de etkilemiş oldu. bunun olmaması için copy yöntemi kullanılmalıdır. 

In [43]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr2 = arr.copy()

In [45]:
arr2[:3] = 1000
arr2

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
narr = np.arange(1,21)
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
narr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [49]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
narr = narr.reshape(5,4)
narr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [51]:
narr[0,0]

1

In [52]:
narr[:,:2] # : ile tüm satırları al ,:2 ile sadece ilk 2 sütunu al

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [53]:
narr[:3,:3] # :3 ilk üç satırı al , :3 ilk üç sütunu al

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [54]:
narr[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
narr[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array leri filtreleme

In [96]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [99]:
booleanarray = arr > 3

In [100]:
arr[booleanarray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [101]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

# numpy arraylerinin temel operasyonları 

In [103]:
import numpy as np

In [104]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [105]:
arr1 + arr2

array([11, 22, 33, 44])

In [106]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [107]:
arr1 * arr2 

array([ 10,  40,  90, 160])

In [108]:
arr1 + 100

array([110, 120, 130, 140])

In [109]:
arr2 - 100

array([-99, -98, -97, -96])

In [110]:
arr1 / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333])

In [111]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [112]:
arr1

array([10, 20, 30, 40])

# Shape Manipulation

In [56]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a = array.ravel() # 3 X 3' lük matrisi tek boyutlu yapmak için .ravel()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array2 = a.reshape(3,3) #eski haline döndürmek amacıyla
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
print(array2.shape)

(3, 3)


In [60]:
array3 = np.array([[1,2],[3,4],[4,5]])
array3

array([[1, 2],
       [3, 4],
       [4, 5]])

In [61]:
array3.reshape(2,3) #reshape yaptık ancak array3 kalıcı olarak değişmez

array([[1, 2, 3],
       [4, 4, 5]])

In [62]:
array3

array([[1, 2],
       [3, 4],
       [4, 5]])

# .resize()

In [64]:
array3.resize((2,3)) #kalıcı olarak dğeiştirir 
array3

array([[1, 2, 3],
       [4, 4, 5]])

In [65]:
array.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
array.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# stacking arrays (arrayleri birleştirme)

In [67]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[-1,-2],[-3,-4]])

In [68]:
array1, array2

(array([[1, 2],
        [3, 4]]),
 array([[-1, -2],
        [-3, -4]]))

In [69]:
# vertical(düşey) birleştirme 

array3 = np.vstack((array1,array2))
array3

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [70]:
#horizontal (yatay) birleştirme

array4 = np.hstack((array1,array2))
array4

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [71]:
array4.sum(), array3.sum()

(0, 0)

# Convert and copy arrays

In [72]:
liste = [1,2,3,4]

array = np.array([5,6,7,8,9])

In [73]:
liste, array

([1, 2, 3, 4], array([5, 6, 7, 8, 9]))

In [74]:
liste

[1, 2, 3, 4]

In [75]:
array

array([5, 6, 7, 8, 9])

In [76]:
np.array(liste) #listeyi, np.array' e dönüştürme 

array([1, 2, 3, 4])

In [77]:
liste2 = list(array) #np.array ini listeye dönüştürme
liste2

[5, 6, 7, 8, 9]

In [79]:
#copy işlemi 

In [80]:
a = np.array([1,2,3])

b = a
c = a

In [81]:
a, b, c 

(array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3]))

In [82]:
b[0] = 9
b

array([9, 2, 3])

In [83]:
a, b, c 

(array([9, 2, 3]), array([9, 2, 3]), array([9, 2, 3]))

In [84]:
d = np.array([1,2,3,4])

e = d.copy() #bu tanım ile bu bize yeni bir alan açar 

In [85]:
d, e 

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [86]:
e[0]=10

In [87]:
d, e 

(array([1, 2, 3, 4]), array([10,  2,  3,  4]))